# Inserts a blank line between shell prompts
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
command_timeout = 600

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
style = "bold cyan"


[character]
success_symbol = " [➜](bold #FFD173) "   # " ❯ "//" ➜ "
error_symbol = " [✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[docker_context]
format = "via [$symbol $context]($style)"
symbol = "Docker"
style = "bold blue"
disabled = false

[elixir]
format = "via [$symbol $version (OTP: $otp_version)]($style)"
symbol = "Elixir"
style = "bold 128"
disabled = false

[nodejs]
format = "via [$symbol $version]($style) "
symbol = "Node.js"
style = "bold green"
disabled = false

[lua]
format = "via [$symbol $version]($style) "
symbol = "Lua"
style = "bold blue"
disabled = false

[python]
format = "via [$symbol $version$venv]($style) "
symbol = "Python"
style = "bold green"
python_binary = "python"
disabled = false

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "⌨ lua"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[⟿ PICKING](bold red)"

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
added_style = "bold green"
deleted_style = "bold red"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"